#!/bin/bash

VOLUME='-v /var/lib/mysql'
DATABASE=wordpress
USER=remo
PASSWORD=remomattei
ROOTPASS=rootpass
docker run -d                        \
    -e MYSQL_USER=$USER              \
    -e MYSQL_PASSWORD=$PASSWORD      \
    -e MYSQL_DATABASE=$DATABASE      \
    -e MYSQL_ROOT_PASSWORD=$ROOTPASS \
    $VOLUME --name=mariadb mariadb
